name: sysrevenv
channels:
  - defaults
dependencies:
  - python=3.9.1
  - seaborn=0.11.1
  - matplotlib=3.3.4
  - pandas=1.2.2
  - numpy=1.19.2
  - ipython=7.20.0
  - ipykernel=5.3.4
  - scikit-learn=0.24.1
  - nltk=3.5
  - pywaffle=0.6.1
